platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'iPets' do
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Runtime'
  pod 'JWTDecode', '~> 3.1'
end
